# main camera params
ib2_interfaces/PowerStatus streaming_status
ib2_interfaces/PowerStatus recording_status
ib2_interfaces/PowerStatus camera_power
ib2_interfaces/PowerStatus microphone_power
float32 zoom
ib2_interfaces/MainCameraResolutionType resolution_type
float32 ev
float32 camera_gain
ib2_interfaces/MainCameraWhiteBalanceMode white_balance_mode
float32 frame_rate
float32 sending_bit_rate
float32 microphone_gain
